server:
  port: 8080

spring:
  application:
    name: FixPoint

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    url: redis://${REDIS_HOST}:6379

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8081/realms/fixpoint-realm
#          opaque token:
#            client-id: fixpoint-client
#            client-secret: EBy7anGEIzWfiV4xHVCgz3XR2PsVJSKm
#            introspection-uri: http://localhost:8081/realms/fixpoint-realm/protocol/openid-connect/token/introspect

      client:
        registration:

          fixpoint-client:
            provider: keycloak
            client-id: fixpoint-client
            client-secret: EBy7anGEIzWfiV4xHVCgz3XR2PsVJSKm
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email

        provider:

          keycloak:
            issuer-uri: http://localhost:8081/realms/fixpoint-realm